### PR TITLE
Fix sorting bug #75

### LINKED ISSUE #75: Fix applicant sorting bug
- Sorting function in `useEffect` in `SearchResults.tsx` is not sorting applicants as expected

### PR DESCRIPTION
**Pull request by GreysonElkins**
#### Type of Change Made 
- [x] bugfix 
- [ ] new feature 
- [ ] breaking change 
- [ ] testing 
- [ ] formatting 
- [ ] styling
#### What's this PR do?
Fixes bug #75 
#### Where should the reviewer start?
line 18 of `searchResults.tsx`
#### How should this be manually tested?
Do some searches and check out how the results are ordered
#### Tests are passing
- [x] 
#### Any background context you want to provide?
I think this was just one of the side effects of sometimes having applicant attributes as objects vs. strings. 
#### What are the relevant tickets?
close #75

### CODE REVIEW

File: src/components/SearchResults/SearchResults.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ const SearchResults: React.FC<RouteComponentProps> = (props) => {
     const filterMatches = (data:SearchResponse) => {
       const attributes = [...data.skills, ...data.values]
       const request = [...query.query.skills, ...query.query.values]
-      return attributes.filter(attribute => request.some(tag => tag.attribute === attribute))
+      return attributes.filter(attribute => request.some(tag => tag.attribute === attribute.attribute))
```
Comment (ErinUntermeyer) [inline src/components/SearchResults/SearchResults.tsx:18]: LOL! Great catch.

**Review by ErinUntermeyer — APPROVED** [review]

**Review by amykarnaze — APPROVED** [review]
:)
